name: CI Pipeline

on:
  push:
    branches:
      - ci-setup  # Run this pipeline only on the ci-setup branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust this based on your project's requirements

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Generate test report
        run: npx jest --coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

