name: Release Automation

on:
  push:
    tags:
      - "v*.*.*"  # Triggers workflow on version tags like v1.0.0

permissions:
  contents: write  # Allows GitHub Actions to create releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Release Notes
        run: |
          echo "# Release Notes" > release-notes.md
          echo "**Release Date:** $(date +'%Y-%m-%d')" >> release-notes.md
          echo "" >> release-notes.md
          echo "## New Features:" >> release-notes.md
          echo "" >> release-notes.md
          echo "## Bug Fixes:" >> release-notes.md
          echo "" >> release-notes.md
          echo "## Known Issues:" >> release-notes.md
          echo "" >> release-notes.md
          echo "## Download Links:" >> release-notes.md
          echo "- **[Source Code](https://github.com/Swaph/bus-reservation-app/releases/download/${{ github.ref_name }}/bus-reservation-${{ github.ref_name }}.tar.gz)**" >> release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-notes.md
          generate_release_notes: false
