name: CI Build & Test

on:
  push:
    branches:
      - main
      - ci-pipeline
  pull_request:
    branches:
      - main
      - ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up SQLite
        run: sudo apt-get install -y sqlite3

      - name: Run tests
        run: npx jest

      - name: Generate Coverage Report
        run: npx jest --coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
